### PR TITLE
Modified for PHPUnit 10

### PR DESCRIPTION
**Pull request by wverhoogt**
Hi,
I needed a version of phpunit-assert-gd for use with PHPUnit 10, so I created this PR. Only composer.json and phpunit.xml needed changes, no other files required changes.

### CODE REVIEW

**Review by meyfa — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution!

CI tests are currently failing since PHPUnit 10 requires PHP v8.1 or later. Can you please update `.github/workflows/main.yml` to run with PHP versions `8.1` and `8.2` instead of the current list?

Since this is a breaking change, I will have to release it as phpunit-assert-gd 4.0.0. Can you also update `README.md` to include a row in the compatibility table for this? I think it should read:

```

| AssertGD version | Supported PHP version | Supported PHPUnit version |
| :--------------- | :-------------------- | :------------------------ |
| 4.*              | >= 8.1                | 10.1 and later            |
| 3.*              | >= 7.3                | 9                         |
| 2.*              | >= 7.2                | 8                         |
| 1.*              | >= 5.3.3              | 4.8.36 - 6.5.0            |
```

**Comment by wverhoogt** [comment]
I have applied your suggested fix, and updated the README.

**Review by meyfa — APPROVED** [review]
Thanks! Changes look good to me.

**Comment by meyfa** [comment]
v4.0.0 is released 🎉

**Pull request merged**
